title: Galerie Hasala by kaz_kamil
author: K. M. H.
email: galeriepodbereski@gmail.com
description: >-
I'm a german-based digital-/traditional-/concept-artist and author.
Feel free to ask me anything.

social:
  twitter: kaz_kamil
  facebook: kaz_kamil
  instagram: kaz_kamil
  github: kaz_kamil

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  images:
    output: true
