# Base configs
baseurl: "https://kazkamil.github.io/"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"

# UI configs
title: "Galerie Hasala"
subtitle: "Feel the Art"
author: "Kamil M. H."
header:
 title: "Galerie Hasala"
 subtitle: "by Kamil M. H."
footer:
 name: "Hey there, my name is Kamil"
 bio: "I am a Artist and a tech enthusiast from Germany"
 instagram: "https://www.instagram.com/kaz_kamil"
